# permissions for end users to view deploymentmaxages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentmaxage-viewer-role
rules:
- apiGroups:
  - tkms0106.example.com
  resources:
  - deploymentmaxages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tkms0106.example.com
  resources:
  - deploymentmaxages/status
  verbs:
  - get
