# permissions for end users to edit deploymentmaxages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentmaxage-editor-role
rules:
- apiGroups:
  - mikutas.example.com
  resources:
  - deploymentmaxages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mikutas.example.com
  resources:
  - deploymentmaxages/status
  verbs:
  - get
