# permissions for end users to view deploymentdeletors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deploymentdeletor-viewer-role
rules:
- apiGroups:
  - mikutas.example.com
  resources:
  - deploymentdeletors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mikutas.example.com
  resources:
  - deploymentdeletors/status
  verbs:
  - get
