apiVersion: mikutas.example.com/v1alpha1
kind: DeploymentDeletor
metadata:
  name: deploymentdeletor-sample
  namespace: laboratory
spec:
  maxAge: 1m
  deployment: 
    name: mysql-client
  selector:
    matchLabels:
      app: mysql-client
