apiVersion: mikutas.example.com/v1alpha1
kind: DeploymentDeletor
metadata:
  name: deploymentdeletor-sample
  namespace: deployment-deletor-system
spec:
  maxAge: 30s
  #deployment:
  #  name: mysql-client
  #  namespace: default
  selector:
    matchLabels:
      app: mysql-client
