// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentDeletor) DeepCopyInto(out *DeploymentDeletor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentDeletor.
func (in *DeploymentDeletor) DeepCopy() *DeploymentDeletor {
	if in == nil {
		return nil
	}
	out := new(DeploymentDeletor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentDeletor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentDeletorList) DeepCopyInto(out *DeploymentDeletorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentDeletor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentDeletorList.
func (in *DeploymentDeletorList) DeepCopy() *DeploymentDeletorList {
	if in == nil {
		return nil
	}
	out := new(DeploymentDeletorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentDeletorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentDeletorSpec) DeepCopyInto(out *DeploymentDeletorSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentDeletorSpec.
func (in *DeploymentDeletorSpec) DeepCopy() *DeploymentDeletorSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentDeletorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentDeletorStatus) DeepCopyInto(out *DeploymentDeletorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentDeletorStatus.
func (in *DeploymentDeletorStatus) DeepCopy() *DeploymentDeletorStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentDeletorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMaxAge) DeepCopyInto(out *DeploymentMaxAge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMaxAge.
func (in *DeploymentMaxAge) DeepCopy() *DeploymentMaxAge {
	if in == nil {
		return nil
	}
	out := new(DeploymentMaxAge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentMaxAge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMaxAgeList) DeepCopyInto(out *DeploymentMaxAgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentMaxAge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMaxAgeList.
func (in *DeploymentMaxAgeList) DeepCopy() *DeploymentMaxAgeList {
	if in == nil {
		return nil
	}
	out := new(DeploymentMaxAgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentMaxAgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMaxAgeSpec) DeepCopyInto(out *DeploymentMaxAgeSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMaxAgeSpec.
func (in *DeploymentMaxAgeSpec) DeepCopy() *DeploymentMaxAgeSpec {
	if in == nil {
		return nil
	}
	out := new(DeploymentMaxAgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentMaxAgeStatus) DeepCopyInto(out *DeploymentMaxAgeStatus) {
	*out = *in
	in.LastDeletedDeployment.DeepCopyInto(&out.LastDeletedDeployment)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentMaxAgeStatus.
func (in *DeploymentMaxAgeStatus) DeepCopy() *DeploymentMaxAgeStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentMaxAgeStatus)
	in.DeepCopyInto(out)
	return out
}
